#!/usr/bin/perl

### Test script specific setup ###
BEGIN {
    $ENV{PATH} = "/home/mark/src/vcardtidy/IGi_3RWB/t" .':'.$ENV{PATH};
    $ENV{SHARE_DIR} //= "/home/mark/src/vcardtidy/IGi_3RWB/share";
}
use lib "/home/mark/src/vcardtidy/IGi_3RWB/lib";
my $ret = do "/home/mark/src/vcardtidy/IGi_3RWB/bin/vcardtidy";
die $@ if $@;
$ret;
