#!/usr/bin/perl

### Test script specific setup ###
BEGIN {
    $ENV{PATH} = "/home/mark/src/vcardtidy/cuXP4aQ8/t" .':'.$ENV{PATH};
    $ENV{SHARE_DIR} //= "/home/mark/src/vcardtidy/cuXP4aQ8/share";
}
use lib "/home/mark/src/vcardtidy/cuXP4aQ8/lib";
my $ret = do "/home/mark/src/vcardtidy/cuXP4aQ8/bin/vcardtidy";
die $@ if $@;
$ret;
